import { LegalPageLayout } from "@/components/legal-page-layout"

export default function TermsAndConditionsPage() {
  return (
    <LegalPageLayout
      title="Terms and Conditions"
      subtitle="These terms govern your use of kahaania.com and all related services offered by NAYANA KAMATH."
    >
      <p className="text-zinc-500">Last updated: March 2, 2026</p>

      <p>
        This document is an electronic record in terms of the Information Technology Act, 2000 and applicable rules
        thereunder, including amended provisions related to electronic records in various statutes as amended by the
        Information Technology Act, 2000. This electronic record is generated by a computer system and does not
        require any physical or digital signatures.
      </p>

      <p>
        This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries
        Guidelines) Rules, 2011, requiring publication of rules and regulations, privacy policy, and terms of use for
        access or usage of the domain name{" "}
        <a className="text-[#f1c60d] hover:underline" href="https://www.kahaania.com/">
          https://www.kahaania.com/
        </a>{" "}
        (owned and operated by NAYANA KAMATH), including related mobile site and mobile application (collectively, the
        "Platform").
      </p>

      <p>
        Your use of the Platform, services, and tools is governed by these terms and conditions ("Terms of Use"), as
        well as applicable policies incorporated herein by reference. If you transact on the Platform, you are subject
        to the policies applicable to that transaction. By merely using the Platform, you contract with the Platform
        Owner and agree to be bound by these Terms of Use and policies.
      </p>

      <p>
        These Terms of Use apply to your use of our website, goods (where applicable), and services (where
        applicable), collectively the "Services". Any additional or conflicting terms proposed by you are expressly
        rejected and shall have no force or effect. These Terms may be modified at any time without assigning any
        reason. You are responsible for periodically reviewing these Terms.
      </p>

      <p>
        For the purpose of these Terms of Use, "you", "your", or "user" means any natural or legal person who has
        agreed to become a user or buyer on the Platform.
      </p>

      <p className="font-semibold text-white">
        ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL TERMS AND CONDITIONS
        LISTED HEREIN.
      </p>

      <h2 className="text-xl text-white font-serif pt-4">Terms of Use</h2>
      <ul className="list-disc pl-6 space-y-2">
        <li>
          To access and use Services, you agree to provide true, accurate, and complete information during and after
          registration, and you are responsible for all actions taken through your registered account.
        </li>
        <li>
          Neither we nor any third parties provide warranties regarding the accuracy, timeliness, performance,
          completeness, or suitability of information and materials on this Platform for any specific purpose.
        </li>
        <li>
          Your use of Services and the Platform is solely at your own risk and discretion. You must independently
          assess whether Services meet your requirements.
        </li>
        <li>
          Platform and Service content is proprietary to us or licensed to us. You have no right to claim intellectual
          property rights, title, or interest in such content, including design, layout, look, and graphics.
        </li>
        <li>
          Unauthorized use of the Platform or Services may result in action under these Terms and applicable law.
        </li>
        <li>You agree to pay charges associated with availing Services.</li>
        <li>
          You agree not to use the Platform or Services for unlawful, illegal, or prohibited purposes under these
          Terms or under applicable Indian or local laws.
        </li>
        <li>
          The Platform may contain links to third-party websites. Access to such links is governed by those third
          parties&apos; terms and policies.
        </li>
        <li>
          On initiating a transaction for Services, you enter into a legally binding and enforceable contract with the
          Platform Owner.
        </li>
        <li>
          You shall indemnify and hold harmless the Platform Owner, affiliates, group companies (if applicable), and
          their officers, directors, agents, and employees from claims, demands, actions, and reasonable legal fees
          arising out of your breach of these Terms, policies, or applicable law, including third-party rights
          violations.
        </li>
        <li>
          Neither party is liable for failure to perform obligations due to force majeure events preventing or delaying
          performance.
        </li>
        <li>These Terms are governed by and construed in accordance with the laws of India.</li>
        <li>All disputes shall be subject to the exclusive jurisdiction of the courts in India.</li>
        <li>
          All concerns or communications relating to these Terms must be sent via the contact information available on
          this website.
        </li>
      </ul>

      <h2 className="text-xl text-white font-serif pt-4">Contact Information</h2>
      <p>
        Email:{" "}
        <a className="text-[#f1c60d] hover:underline" href="mailto:getmykahaania@gmail.com">
          getmykahaania@gmail.com
        </a>
      </p>
    </LegalPageLayout>
  )
}
